name: Build

on: [push]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup-java
        uses: actions/setup-java@v2
        with:
          cache: maven
          distribution: 'temurin'
          java-version: '16'
      - name: build-maven
        run: mvn --batch-mode --update-snapshots verify
